// Command mock-ai is a tiny deterministic stand-in for an AI report generator.
//
// It exposes POST /generate which accepts a JSON body describing a financial dataset
// and returns a JSON body containing a generated markdown report. The output is fully
// deterministic (no API key, no network) so the workshop runs anywhere.
//
// Optionally, if AI_PROVIDER=openai and OPENAI_API_KEY is set, it forwards the prompt to
// the OpenAI Chat Completions API instead. This is the "real provider toggle" — it is not
// required for the workshop and is provided as an extension.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"time"
)

type generateRequest struct {
	Title        string `json:"title"`
	Dataset      string `json:"dataset"`
	Instructions string `json:"instructions"`
}

type generateResponse struct {
	Report   string `json:"report"`
	Provider string `json:"provider"`
}

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})
	mux.HandleFunc("/generate", handleGenerate)

	addr := ":8080"
	log.Printf("mock-ai listening on %s (provider=%s)", addr, providerName())
	srv := &http.Server{
		Addr:              addr,
		Handler:           mux,
		ReadHeaderTimeout: 10 * time.Second,
	}
	log.Fatal(srv.ListenAndServe())
}

func providerName() string {
	if strings.EqualFold(os.Getenv("AI_PROVIDER"), "openai") && os.Getenv("OPENAI_API_KEY") != "" {
		return "openai"
	}
	return "mock"
}

func handleGenerate(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	body, err := io.ReadAll(io.LimitReader(r.Body, 1<<20))
	if err != nil {
		http.Error(w, "cannot read body", http.StatusBadRequest)
		return
	}
	var req generateRequest
	if err := json.Unmarshal(body, &req); err != nil {
		http.Error(w, "invalid JSON", http.StatusBadRequest)
		return
	}
	if req.Title == "" {
		req.Title = "Untitled Report"
	}

	var report string
	provider := providerName()
	if provider == "openai" {
		report, err = generateWithOpenAI(req)
		if err != nil {
			log.Printf("openai call failed, falling back to mock: %v", err)
			report = generateMock(req)
			provider = "mock(fallback)"
		}
	} else {
		report = generateMock(req)
	}

	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(generateResponse{Report: report, Provider: provider})
}

// generateMock builds a deterministic, professional-looking financial report in markdown.
func generateMock(req generateRequest) string {
	lines := splitNonEmpty(req.Dataset)
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", req.Title)
	fmt.Fprintf(&b, "_Generated by the mock AI report engine._\n\n")
	fmt.Fprintf(&b, "## Executive Summary\n\n")
	fmt.Fprintf(&b,
		"This report analyses the provided dataset of %d line(s). Overall the figures "+
			"indicate a stable financial position with several actionable opportunities "+
			"highlighted below.\n\n", len(lines))

	if req.Instructions != "" {
		fmt.Fprintf(&b, "## Analysis Focus\n\n%s\n\n", req.Instructions)
	}

	fmt.Fprintf(&b, "## Dataset\n\n")
	if len(lines) == 0 {
		fmt.Fprintf(&b, "_No structured data was provided._\n\n")
	} else {
		for i, l := range lines {
			fmt.Fprintf(&b, "%d. %s\n", i+1, l)
		}
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "## Key Findings\n\n")
	fmt.Fprintf(&b, "- Revenue trends are consistent with prior reporting periods.\n")
	fmt.Fprintf(&b, "- Cost structure remains within expected bounds.\n")
	fmt.Fprintf(&b, "- No material anomalies detected in the supplied figures.\n\n")

	fmt.Fprintf(&b, "## Recommendations\n\n")
	fmt.Fprintf(&b, "1. Continue monitoring the largest cost centres.\n")
	fmt.Fprintf(&b, "2. Reinvest a portion of the surplus into growth initiatives.\n")
	fmt.Fprintf(&b, "3. Re-run this report next quarter to track the trend.\n\n")

	fmt.Fprintf(&b, "---\n\n_This is a workshop demo. Figures are illustrative._\n")
	return b.String()
}

func splitNonEmpty(s string) []string {
	var out []string
	for _, l := range strings.Split(s, "\n") {
		if t := strings.TrimSpace(l); t != "" {
			out = append(out, t)
		}
	}
	return out
}

// generateWithOpenAI forwards the prompt to OpenAI. Optional extension path.
func generateWithOpenAI(req generateRequest) (string, error) {
	model := os.Getenv("OPENAI_MODEL")
	if model == "" {
		model = "gpt-4o-mini"
	}
	prompt := fmt.Sprintf(
		"Write a concise financial report titled %q. Instructions: %s. Dataset:\n%s",
		req.Title, req.Instructions, req.Dataset)

	payload := map[string]any{
		"model": model,
		"messages": []map[string]string{
			{"role": "system", "content": "You are a financial analyst that writes clear markdown reports."},
			{"role": "user", "content": prompt},
		},
	}
	buf, _ := json.Marshal(payload)

	httpReq, err := http.NewRequest(http.MethodPost, "https://api.openai.com/v1/chat/completions", bytes.NewReader(buf))
	if err != nil {
		return "", err
	}
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("Authorization", "Bearer "+os.Getenv("OPENAI_API_KEY"))

	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Do(httpReq)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("openai returned %d: %s", resp.StatusCode, string(respBody))
	}

	var parsed struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.Unmarshal(respBody, &parsed); err != nil {
		return "", err
	}
	if len(parsed.Choices) == 0 {
		return "", fmt.Errorf("openai returned no choices")
	}
	return parsed.Choices[0].Message.Content, nil
}
