// Package v1alpha1 contains the Go types for the ReportRequest custom resource.
// These mirror the CRD's OpenAPI schema in manifests/report-crd.yaml.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// GroupVersion is the group/version for the ReportRequest API.
var GroupVersion = schema.GroupVersion{Group: "reports.workshop.io", Version: "v1alpha1"}

// SchemeBuilder registers the types with a runtime.Scheme.
var SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

// AddToScheme adds the types in this package to a scheme.
var AddToScheme = SchemeBuilder.AddToScheme

func init() {
	SchemeBuilder.Register(&ReportRequest{}, &ReportRequestList{})
}

// Phase is the lifecycle phase of a ReportRequest.
type Phase string

const (
	PhasePending    Phase = "Pending"
	PhaseProcessing Phase = "Processing"
	PhaseCompleted  Phase = "Completed"
	PhaseFailed     Phase = "Failed"
)

// ReportRequestSpec is the desired state declared by the user.
type ReportRequestSpec struct {
	Title        string `json:"title"`
	Dataset      string `json:"dataset"`
	Instructions string `json:"instructions,omitempty"`
	Format       string `json:"format,omitempty"`
}

// ReportRequestStatus is the observed state, owned by the controller.
type ReportRequestStatus struct {
	Phase              Phase        `json:"phase,omitempty"`
	Message            string       `json:"message,omitempty"`
	JobName            string       `json:"jobName,omitempty"`
	PDFObjectKey       string       `json:"pdfObjectKey,omitempty"`
	ObservedGeneration int64        `json:"observedGeneration,omitempty"`
	StartTime          *metav1.Time `json:"startTime,omitempty"`
	CompletionTime     *metav1.Time `json:"completionTime,omitempty"`
}

// ReportRequest is the Schema for the reportrequests API.
type ReportRequest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ReportRequestSpec   `json:"spec,omitempty"`
	Status ReportRequestStatus `json:"status,omitempty"`
}

// ReportRequestList contains a list of ReportRequest.
type ReportRequestList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReportRequest `json:"items"`
}

// --- runtime.Object / DeepCopy implementations -----------------------------------------
// These are normally generated by controller-gen. They are written by hand here so the
// project is self-contained and easy to read in a workshop.

func (in *ReportRequest) DeepCopyInto(out *ReportRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ReportRequest) DeepCopy() *ReportRequest {
	if in == nil {
		return nil
	}
	out := new(ReportRequest)
	in.DeepCopyInto(out)
	return out
}

func (in *ReportRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ReportRequestStatus) DeepCopyInto(out *ReportRequestStatus) {
	*out = *in
	if in.StartTime != nil {
		out.StartTime = in.StartTime.DeepCopy()
	}
	if in.CompletionTime != nil {
		out.CompletionTime = in.CompletionTime.DeepCopy()
	}
}

func (in *ReportRequestList) DeepCopyInto(out *ReportRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]ReportRequest, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *ReportRequestList) DeepCopy() *ReportRequestList {
	if in == nil {
		return nil
	}
	out := new(ReportRequestList)
	in.DeepCopyInto(out)
	return out
}

func (in *ReportRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
