// Command worker is executed inside the Job that the controller creates for each
// ReportRequest. It performs the actual work:
//
//  1. Reads the report parameters from environment variables (set by the controller).
//  2. Calls the mock-ai service to generate a markdown report.
//  3. Renders that report into a PDF.
//  4. Uploads the PDF to MinIO under the configured object key.
//
// A small artificial delay makes the "Processing" phase visible in the UI and in k9s.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func main() {
	cfg := loadConfig()

	log.Printf("worker starting for report %q -> object %q", cfg.Title, cfg.ObjectKey)

	// Make the work visibly take a few seconds so participants can watch the status change.
	delay := envDurationSeconds("PROCESSING_DELAY_SECONDS", 5)
	log.Printf("simulating work for %s", delay)
	time.Sleep(delay)

	report, err := generateReport(cfg)
	if err != nil {
		log.Fatalf("failed to generate report: %v", err)
	}

	pdf, err := renderPDF(cfg.Title, report)
	if err != nil {
		log.Fatalf("failed to render PDF: %v", err)
	}

	if err := uploadPDF(cfg, pdf); err != nil {
		log.Fatalf("failed to upload PDF: %v", err)
	}

	log.Printf("done: uploaded %d bytes to %s/%s", len(pdf), cfg.Bucket, cfg.ObjectKey)
}

type config struct {
	Title        string
	Dataset      string
	Instructions string
	ObjectKey    string

	MockAIURL string

	MinioEndpoint  string
	MinioAccessKey string
	MinioSecretKey string
	Bucket         string
	MinioUseSSL    bool
}

func loadConfig() config {
	return config{
		Title:          os.Getenv("REPORT_TITLE"),
		Dataset:        os.Getenv("REPORT_DATASET"),
		Instructions:   os.Getenv("REPORT_INSTRUCTIONS"),
		ObjectKey:      mustEnv("OBJECT_KEY"),
		MockAIURL:      envOrDefault("MOCK_AI_URL", "http://mock-ai.report-queue.svc.cluster.local:8080"),
		MinioEndpoint:  envOrDefault("MINIO_ENDPOINT", "minio.report-queue.svc.cluster.local:9000"),
		MinioAccessKey: envOrDefault("MINIO_ACCESS_KEY", "minioadmin"),
		MinioSecretKey: envOrDefault("MINIO_SECRET_KEY", "minioadmin"),
		Bucket:         envOrDefault("MINIO_BUCKET", "reports"),
		MinioUseSSL:    os.Getenv("MINIO_USE_SSL") == "true",
	}
}

type aiRequest struct {
	Title        string `json:"title"`
	Dataset      string `json:"dataset"`
	Instructions string `json:"instructions"`
}

type aiResponse struct {
	Report   string `json:"report"`
	Provider string `json:"provider"`
}

func generateReport(cfg config) (string, error) {
	reqBody, _ := json.Marshal(aiRequest{
		Title:        cfg.Title,
		Dataset:      cfg.Dataset,
		Instructions: cfg.Instructions,
	})

	client := &http.Client{Timeout: 90 * time.Second}
	resp, err := client.Post(cfg.MockAIURL+"/generate", "application/json", bytes.NewReader(reqBody))
	if err != nil {
		return "", fmt.Errorf("calling mock-ai: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("mock-ai returned status %d", resp.StatusCode)
	}
	var parsed aiResponse
	if err := json.NewDecoder(resp.Body).Decode(&parsed); err != nil {
		return "", fmt.Errorf("decoding mock-ai response: %w", err)
	}
	log.Printf("report generated by provider=%s", parsed.Provider)
	return parsed.Report, nil
}

// renderPDF turns the (markdown-ish) report text into a simple, readable PDF.
// It is intentionally lightweight: headings become larger text, list items get a bullet,
// everything else is body text.
func renderPDF(title, report string) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()

	pdf.SetFont("Helvetica", "B", 18)
	pdf.MultiCell(0, 9, sanitize(title), "", "L", false)
	pdf.Ln(2)

	for _, raw := range strings.Split(report, "\n") {
		line := strings.TrimRight(raw, " ")
		switch {
		case strings.HasPrefix(line, "# "):
			pdf.SetFont("Helvetica", "B", 16)
			pdf.Ln(3)
			pdf.MultiCell(0, 8, sanitize(strings.TrimPrefix(line, "# ")), "", "L", false)
		case strings.HasPrefix(line, "## "):
			pdf.SetFont("Helvetica", "B", 13)
			pdf.Ln(2)
			pdf.MultiCell(0, 7, sanitize(strings.TrimPrefix(line, "## ")), "", "L", false)
		case strings.HasPrefix(line, "- "):
			pdf.SetFont("Helvetica", "", 11)
			pdf.MultiCell(0, 6, "  •  "+sanitize(strings.TrimPrefix(line, "- ")), "", "L", false)
		case strings.TrimSpace(line) == "---":
			pdf.Ln(2)
			y := pdf.GetY()
			pdf.Line(20, y, 190, y)
			pdf.Ln(2)
		case strings.TrimSpace(line) == "":
			pdf.Ln(3)
		default:
			pdf.SetFont("Helvetica", "", 11)
			pdf.MultiCell(0, 6, sanitize(line), "", "L", false)
		}
	}

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// sanitize replaces characters the core PDF fonts can't encode and strips simple markdown.
func sanitize(s string) string {
	s = strings.ReplaceAll(s, "**", "")
	s = strings.ReplaceAll(s, "_", "")
	s = strings.ReplaceAll(s, "•", "-")
	// Replace any remaining non-Latin1 runes with '?'
	var b strings.Builder
	for _, r := range s {
		if r > 255 {
			b.WriteRune('?')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func uploadPDF(cfg config, data []byte) error {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	client, err := minio.New(cfg.MinioEndpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(cfg.MinioAccessKey, cfg.MinioSecretKey, ""),
		Secure: cfg.MinioUseSSL,
	})
	if err != nil {
		return fmt.Errorf("creating minio client: %w", err)
	}

	exists, err := client.BucketExists(ctx, cfg.Bucket)
	if err != nil {
		return fmt.Errorf("checking bucket: %w", err)
	}
	if !exists {
		if err := client.MakeBucket(ctx, cfg.Bucket, minio.MakeBucketOptions{}); err != nil {
			return fmt.Errorf("creating bucket: %w", err)
		}
	}

	_, err = client.PutObject(ctx, cfg.Bucket, cfg.ObjectKey,
		bytes.NewReader(data), int64(len(data)),
		minio.PutObjectOptions{ContentType: "application/pdf"})
	if err != nil {
		return fmt.Errorf("uploading object: %w", err)
	}
	return nil
}

func mustEnv(key string) string {
	v := os.Getenv(key)
	if v == "" {
		log.Fatalf("required environment variable %s is not set", key)
	}
	return v
}

func envOrDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func envDurationSeconds(key string, def int) time.Duration {
	if v := os.Getenv(key); v != "" {
		var n int
		if _, err := fmt.Sscanf(v, "%d", &n); err == nil && n >= 0 {
			return time.Duration(n) * time.Second
		}
	}
	return time.Duration(def) * time.Second
}
