// Package v1alpha1 contains the Go types for the Bucket custom resource.
//
// Bucket is the workshop's second custom resource. Where ReportRequest spawns a Job,
// Bucket shows the *other* big operator pattern: the controller talks directly to an
// external system (MinIO) and provisions a real resource there. The custom resource is a
// domain object — "I want an object-storage bucket" — and Kubernetes becomes the API that
// fulfils it. This is exactly how Crossplane and the AWS/GCP/Azure operators work.
//
// These types mirror the CRD's OpenAPI schema in manifests/bucket-crd.yaml.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// GroupVersion is the group/version for the Bucket API. A *different* group from
// reports.workshop.io — this is a separate domain ("storage"), which is the point: the
// cluster grows new, vendor-neutral APIs as you add operators.
var GroupVersion = schema.GroupVersion{Group: "storage.workshop.io", Version: "v1alpha1"}

// SchemeBuilder registers the types with a runtime.Scheme.
var SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

// AddToScheme adds the types in this package to a scheme.
var AddToScheme = SchemeBuilder.AddToScheme

func init() {
	SchemeBuilder.Register(&Bucket{}, &BucketList{})
}

// Phase is the lifecycle phase of a Bucket.
type Phase string

const (
	PhasePending     Phase = "Pending"
	PhaseReady       Phase = "Ready"
	PhaseFailed      Phase = "Failed"
	PhaseTerminating Phase = "Terminating"
)

// AccessPolicy controls anonymous access to the bucket's objects.
type AccessPolicy string

const (
	// AccessPrivate removes any anonymous policy: only authenticated callers can read.
	AccessPrivate AccessPolicy = "private"
	// AccessPublicRead allows anonymous GET on objects (s3:GetObject).
	AccessPublicRead AccessPolicy = "public-read"
)

// DeletionPolicy decides what happens to the real MinIO bucket when the Bucket resource is
// deleted. Owner references can't garbage-collect resources that live *outside* Kubernetes,
// so the controller uses a finalizer to honour this policy.
type DeletionPolicy string

const (
	// DeletionRetain leaves the MinIO bucket (and its objects) in place.
	DeletionRetain DeletionPolicy = "Retain"
	// DeletionDelete removes the MinIO bucket (and its objects) before the resource is gone.
	DeletionDelete DeletionPolicy = "Delete"
)

// BucketSpec is the desired state declared by the user.
type BucketSpec struct {
	// BucketName is the name of the bucket to create in MinIO.
	BucketName string `json:"bucketName"`
	// AccessPolicy controls anonymous read access. Defaults to "private".
	AccessPolicy AccessPolicy `json:"accessPolicy,omitempty"`
	// Quota is the maximum total size of the bucket, as a Kubernetes quantity
	// (e.g. "100Mi", "2Gi"). Empty means no quota.
	Quota string `json:"quota,omitempty"`
	// DeletionPolicy decides whether deleting this resource also deletes the MinIO
	// bucket. Defaults to "Retain".
	DeletionPolicy DeletionPolicy `json:"deletionPolicy,omitempty"`
}

// BucketStatus is the observed state, owned by the controller.
type BucketStatus struct {
	Phase              Phase        `json:"phase,omitempty"`
	Message            string       `json:"message,omitempty"`
	Endpoint           string       `json:"endpoint,omitempty"`
	QuotaBytes         int64        `json:"quotaBytes,omitempty"`
	AppliedPolicy      AccessPolicy `json:"appliedPolicy,omitempty"`
	ObservedGeneration int64        `json:"observedGeneration,omitempty"`
	ReadyTime          *metav1.Time `json:"readyTime,omitempty"`
}

// Bucket is the Schema for the buckets API.
type Bucket struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BucketSpec   `json:"spec,omitempty"`
	Status BucketStatus `json:"status,omitempty"`
}

// BucketList contains a list of Bucket.
type BucketList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Bucket `json:"items"`
}

// --- runtime.Object / DeepCopy implementations -----------------------------------------
// Normally generated by controller-gen; hand-written here so the project is self-contained.

func (in *Bucket) DeepCopyInto(out *Bucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Bucket) DeepCopy() *Bucket {
	if in == nil {
		return nil
	}
	out := new(Bucket)
	in.DeepCopyInto(out)
	return out
}

func (in *Bucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BucketStatus) DeepCopyInto(out *BucketStatus) {
	*out = *in
	if in.ReadyTime != nil {
		out.ReadyTime = in.ReadyTime.DeepCopy()
	}
}

func (in *BucketList) DeepCopyInto(out *BucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]Bucket, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *BucketList) DeepCopy() *BucketList {
	if in == nil {
		return nil
	}
	out := new(BucketList)
	in.DeepCopyInto(out)
	return out
}

func (in *BucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
